name: "✨ Feature Request"
description: "Suggest a new feature or improvement for the project."
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: textarea
    id: summary
    attributes:
      label: "🌟 Feature Summary"
      description: "Provide a clear and concise summary of the feature you are requesting."
      placeholder: "What feature do you want to see?"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "💡 Motivation"
      description: "Explain the problem you're facing and how this feature would help solve it."
      placeholder: "What problem does this solve?"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "🚀 Proposed Solution"
      description: "Describe the solution you'd like to see, including how it would work."
      placeholder: "How should this feature work?"
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "🔄 Alternatives Considered"
      description: "Have you considered any alternative solutions or workarounds?"
      placeholder: "List any alternative solutions or workarounds you've tried."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "📎 Additional Context"
      description: "Add any other context, images, or references related to the feature request."
      placeholder: "Links, screenshots, or references that support your idea."
    validations:
      required: false
